### ISSUE TITLE
Sticky State Performance: Too Many Watchers

### ISSUE THREAD

**Issue by vahan-hartooni** [christopherthielen/ui-router-extras#117]
The sticky state extra was based on the tab use case, however the app will slow down when there are too many tabs. 

I looked into how [sticky state example](http://christopherthielen.github.io/ui-router-extras/example/sticky/index.html) was achieved and I see that the view and scope is retained by hiding the ui-view containers instead of swapping out templates. However, there is a glaring performance issue with this strategy: since the scope is retained, so are the watchers. In the example, run [this snippet](https://gist.github.com/kentcdodds/31c90402750572107922#file-get-watchers-js) in the console to get the number of watchers in the page. You'll notice that as you dive deep into each state, the number of watchers goes up. You can imagine how this can be an issue on a production tab system where some of those tabs might have a thousand entry table!

To have a performant tab system, the $$watchers inside the hidden views (inactive states) would need to be "paused." Unfortunately, Angular has no way of doing this. I propose that when we leave an active state, Sticky State will go through the state's scope, remove and store all the $$watchers in a separate tree structure. When we return to that state, the $$watchers are reapplied to the active state's scope. 

Does anyone foresee any problems with this proposal? 

Are there any alternative ways we can prevent Angular from checking the watchers in the inactive states?

**Comment by christopherthielen** [comment]
Sticky States intentionally leaves the DOM and scopes intact.  The inactive states are still live, respond to events, etc.  Even in the "tabs" use case, we may need to respond to interactions via HTTP or events.  In other use cases, we don't even hide the inactive views.  While the demo site hides inactive tabs using ng-show, we don't need to and could have even conceivably have interaction between two parallel views.

I'm concerned that "pausing" inactive views may add complexity and invite obscure timing bugs into applications.  However, I understand the desire for the functionality.  

Perhaps you can code something up using the the `state.onInactivate` and `state.onReactivate` callbacks (although they do not have access to $scope, due to being state-based, not view-based).  I would be happy to continue this discussion, or offer assistance or even additional hooks to ui-router-extras, but I'm hesitant about taking on the burden of officially supporting that feature.

One more thing to consider:  I think ionic framework may already do what you describe.  They call it "view caching".  Read http://ionicframework.com/docs/api/directive/ionNavView/ (search for "Caching").  Perhaps you can use that portion of ionic, or reverse engineer it.

**Comment by vahan-hartooni** [comment]
Thanks for the feedback! I agree, after some more research, watch pausing seems to be an issue [that is better addressed in the core Angular framework](https://github.com/angular/angular.js/issues/5301), so best not to complicate sticky state as it appears you have other use cases to handle besides tabs.
