### ISSUE TITLE
Handling nested views inside dialog

### ISSUE THREAD

**Issue by mail2asik** [christopherthielen/ui-router-extras#125]
We are handling nested views in page level and it works fine. but we are not able to display nested views inside dialog.

I have tried using ui-router as well with ui-roter-extras using sticky state

ui-router
=======
http://plnkr.co/edit/E2j471?p=preview

ui-router with ui-router-extras (sticky state)
==================================
http://plnkr.co/edit/6iL0mq?p=preview

In the above samples, Check the following navigation's

Click "First Page" > Click "Popup Page" > Click "Child Page1" or "Child Page 2"

Child Pages are not getting displayed inside dialog.

**Comment by christopherthielen** [comment]
This seems to be a side effect of how bootstrap places the modal DIV as a child of `<body>` tag.  The ui-view tag thinks it is a top-level ui-view because it walks up the DOM looking for its parent ui-view context, and only finds the root.

If you change your state declarations to target named ui-views in the root context, then they populate.


```
  $stateProvider.state('first.popup.child1', {
    url: '/child1',
    views: {
      'child1View@': {
        templateUrl: 'child1.html'
      }
    }
  });
  

  $stateProvider.state('first.popup.child2', {
    url: '/child2',
    views: {
      'child2View@': {
        templateUrl: 'child2.html'
      }
    }
  });
```

This isn't a bug in ui-router-extras, not ui-router really.  This is an unintended interaction between bootstrap-ui modal and ui-router ui-view logic. The only way to do this "the right way" would be to get the modal div inserted into the DOM as a child element of the parent ui-view.

**Comment by mail2asik** [comment]
Thank you Chris!! As you said, Absolute named view (putting @ end of the name) is working fine.
