### ISSUE TITLE
0.0.11, FutureStates - "name" and "url" are now both required?

### ISSUE THREAD

**Issue by maximumduncan** [christopherthielen/ui-router-extras#129]
In 0.0.10, it was possible to specify either url *or* name when defining a future state - a fact which my application depends on.
With 0.0.11 it appears that the `futureState()` method of `$futureStateProvider` makes assumptions that 'name' *and* 'url' will always be specified.

It appears that 'name' is required in order to resolve the parent state relationship, and 'url' is required to support urls being built up from appended parent urls. Unfortunately most of my "parent" states are abstract and therefore have no url. Am I correct in assuming that FutureStates doesn't support abstract states?
This wasn't an issue with 0.0.10 because it appeared that didn't need to specify the "name" - as futurestates wasn't trying to resolve the parent<>child relationships - just specifying "url" worked fine for me.

**Comment by christopherthielen** [comment]
@maximumduncan `name` (`stateName`) and `url` (`urlPrefix`) have always been considered required.  It was just luck that it worked for you with one or the other in 0.0.10.  May I ask why you object to providing the future state name?

**Comment by christopherthielen** [comment]
The other half of your question, I haven't tested future states as substates to abstract states.  I will look into that.

**Comment by christopherthielen** [comment]
I think this commit: 31ca73bdc07ac80b53e9ec76f7f4eca268461fa2 allows abstract parent state.  I added a test for this scenario and it's passing.

**Comment by maximumduncan** [comment]
@christopherthielen - thanks for commenting on this, I will have a look at that commit and get back to you.

> May I ask why you object to providing the future state name?

Essentially because there may be many states loaded (a hierarchy where some are abstract) at a single URL. If I need to specify a "name" in `$futureStates`, then I also need to specify that state's parent, and the parent's parent etc. Essentially it seems that my whole state hierarchy needs to be duplicated into $futureStates - whereas before a single URL would've sufficed.

**Comment by maximumduncan** [comment]
I've had a look at that commit and it's associated test, and it appears that this approach will work *if* the abstract states are declared statically (in `$stateProvider`) when the application is loaded. I can't see this working if the abstract states themselves are also considered "future" states.

This is what I have in my app - the whole hierarchy of states, including the abstract ones, shouldn't be defined at application load time; I'd like all those states to be future states and therefore it seems they all have to be defined in `$futureStateProvider`. Even if I was to try and do that (which would lead to quite a bit of duplication) I think that `$futureStateProvider` will complain as it doesn't look like it supports abstract states because it each state requires a url.

**Comment by christopherthielen** [comment]
@maximumduncan in order to support $state.go('some.future.state.nested.deeply') [as opposed to $location.url('/some/url/nested/deeply')], future states **must** have names.  

These bullet points may help you find a working solution:

- abstract states *may* have urls
- you may define future states which lazy load to abstract states
- you may register a single future state placeholder which, when realized via its factory, lazy loads to an entire hierarchy of full states (i.e., a module)
- you may register a future state hierarchy and also register nested sub-hierarchies or sub-states; they will be chained and lazy loaded in the correct order when the nested url or state is requested.  (https://github.com/christopherthielen/ui-router-extras/blob/master/src/futureState.js#L120) 
  - A nested chained future state may be a deeply nested grandchild of a parent future state, not necessarily a direct child
  - Chained future states will concatenate their future urls together, so define your urls wisely (https://github.com/christopherthielen/ui-router-extras/blob/master/src/futureState.js#L57)
- Future state urls may be declared using "^" for absolute url matching (https://github.com/christopherthielen/ui-router-extras/blob/master/src/futureState.js#L61)

**Comment by hworld** [comment]
I'm having similar issue and your fix gets us halfway there. I believe that future states should always have names, so no issue there. And the fix for optional URLs works in half the cases. Here's my situation:

```js
$futureStateProvider
	.futureState( {
		name: 'auth',
	} )
	.futureState( {
		name: 'auth.login',
		url: '/login',
	} );

// The states that will be lazy loaded.
$stateProvider
	.state( 'auth', {
	    abstract: true,
	} )
	.state( 'auth.login', {
		url: '/login',
	} );
```

Basically, I don't have a "top" state like in the tests. I have a bunch of auth related states that are nested to include the template and various other resolves, etc. The issue is that I don't want to have a top-level URL so that I can keep login/join URLS short and clean. However, I want to lazy load the whole section of states.

It _almost_ works. It seems what is happening is that when registering the `auth` state with future states it fails at the line with `futureState.url.charAt(0)`. I believe that's what @maximumduncan was saying. It would only work if I had set `auth` as a non-future-state through $stateProvider, since then it wouldn't try to find the URL for it.

What would be ideal is that it just skips the URL generation for it if possible. `$state.go` would work since the name is registered just fine.

**Comment by christopherthielen** [comment]
@hworld can you speecify `url: ""` on your url-less future states?

**Comment by hworld** [comment]
When I did that, it was attempting to load in the `auth` future state any time there was a state not found. I think since the URL of `''` matched any URL. I'm thinking that any time a state wasn't found, it would attempt to load all my abstract states in.

**Comment by maximumduncan** [comment]
Thanks for everyone's help.

I've had some time to go back to this and I've managed to make it work with one minor change to the library. I've created a pull request with this change in it (https://github.com/christopherthielen/ui-router-extras/pull/167) for your review.
