### ISSUE TITLE
Sticky states get reloaded unexpectedly

### ISSUE THREAD

**Issue by arthastft** [christopherthielen/ui-router-extras#131]
Hello christopher,
Say I have following states structure:
```javascript
parent1: { sticky: true }
parent1.child1: { sticky: true }
parent1.child2: { sticky: false }

parent2: { sticky: false }
parent2.child1: { sticky: false }
```
When I do: `parent1.child1` => `parent2.child1` => `parent1.child1`, it works normally.
But when: `parent1.child1` => `parent2.child1` => `parent1.child2` => `parent1.child1`, `parent1.child1` gets reloaded.

**Comment by christopherthielen** [comment]
@arthastft could you put this in a plunk for me?   I agree that behavior seems wrong

**Comment by arthastft** [comment]
Of course, here: http://plnkr.co/edit/n4UEJ4qATykdUxEoez3v?p=preview.
I've found out a workaround that if I set all the states parallel to parent1.child1 to sticky, the problem goes away. Not ideal though.

**Comment by christopherthielen** [comment]
Yes, I see how this is happening now.  
https://github.com/christopherthielen/ui-router-extras/blob/master/src/stickyStateProvider.js#L180

"Deepest reactivate" is intended for when you directly reactivate a sticky state (without DSR), it should exit the children of that state.  For example, from `parent1.child1` to `parent1` should exit `parent1.child`.  Your use case causes `deepestReactivate` to be populated with your `parent1` state, but then the logic for the use case above kicks in and removes `parent1.child` form the inactives list.  This will take a little bit of rework.

**Comment by arthastft** [comment]
Hi christopher,
I'm afraid that the problem is still here.
I just updated the plunker to reference 0.0.13: http://plnkr.co/edit/n4UEJ4qATykdUxEoez3v?p=preview

**Comment by christopherthielen** [comment]
@arthastft thanks for helping me fix a longstanding bug in ui-router-extras!

My unit tests don't currently catch your scenario (currently only a full integration test will, like your plunk)



Here is the analysis of the issue for future reference:

- State A is inactivated
- Another transition will reactivate State A, and enter State B
- State B needs to be set up.  Part of this is loading resolves and calling `$view.load()` to retrieve template/controller, etc
- `$view.load()` fires `$viewContentLoading`
  - `ui-view` responds to `$viewContentLoading` (and `$stateChangeSuccess`), and checks if it needs to update itself
    - It short circuits if the current locals object is the same reference as the previous locals
    - It looks at `$state.$current.locals[viewname]` to load `previousLocals`
    - Because the transition is in-procoess, `$state.$current` still has the `fromState` and its locals.
    - The `fromState` locals does not include the view for the state being reactivated, so the view reloads itself

In order to fix this, I had to provide the "view's locals for states being reactivated" during the transition.  I did this by defining another object and making it the prototype of `__inactives.locals`. The locals for states being reactivated are placed on that object, then removed when the transition is done.  Then, the `ui-view` for states being reactivated will short-circuit when `$viewContentLoading` is fired.

**Comment by fdiazaguirre** [comment]
I created a modal with two tabs but the partials are not showing.

Here is the plunk: http://plnkr.co/edit/ukjUYS?p=info

Thanks in advance!
