### ISSUE TITLE
Add null check for states resolve

### ISSUE THREAD

**Issue by amcdnl** [christopherthielen/ui-router-extras#149]
In my proof-of-concept I was able to use [ocLazyLoad](https://github.com/ocombe/ocLazyLoad) to resolve the module/states automatically.  This eliminates the need for: https://github.com/christopherthielen/ui-router-extras/blob/master/src/future.js#L217

I was able to nix this in my project: https://github.com/amcdnl/systemjs-test/blob/master/src/common/utils/lazy-routes.js#L228 cleaning up the need for returning the module and special code handling for that.  States are handled normally like: https://github.com/amcdnl/systemjs-test/blob/master/src/app/login/login.js#L15 ... the magic comes in here:  https://github.com/amcdnl/systemjs-test/blob/master/src/common/utils/routing.js#L22

I don't think this will work for angularAMD project but since there is a solution out there that can resolve this, I think a nice compromise would just be adding a null check around it.  Thoughts?

**Comment by christopherthielen** [comment]
@amcdnl i think I'm already doing this upstream in the process due to issue #99, so a null check should be unnecessary.    

https://github.com/christopherthielen/ui-router-extras/blob/master/src/future.js#L131 in commit 48995fb3788a684847822ffb1334e5bf07102d32 means `lazyLoadState` always resolves to an array (empty or with states) which will then be iterated over 0 to n times.

**Comment by christopherthielen** [comment]
Oh, I see what's happening now.  You're resolving your promise with the module in the code you pointed me to.  That's being pushed to the array.

In your Future State Factory, just resolve the module with 'null' or 'undefined' and it should work.

**Comment by amcdnl** [comment]
Ah okay; didn't know resolving undefined would still make it go through the same flow.
