### ISSUE TITLE
Initial deep state through $deepStateRedirect

### ISSUE THREAD

**Issue by jvisser** [christopherthielen/ui-router-extras#150]
Hi, 

I was wondering if its possible to set an initial deep state, for example:

```javascript
$deepStateRedirect.setInitialState("state1", "state1.childstate11.childstate111");
```

When state1 is first entered it wil direct to state1.childstate11.childstate111.

Thanks,
jvisser

**Comment by christopherthielen** [comment]
Definitely. This has been in my todo for some time.

**Comment by jvisser** [comment]
Just tested this, works like a charm :)
Thanks!

**Comment by christopherthielen** [comment]
sweet. I hadn't even pushed the new docs yet, hah!

http://christopherthielen.github.io/ui-router-extras/#/dsr

**Comment by jvisser** [comment]
Not sure if this is a new issue or related to this one. I noticed a sticky leaf state with parameter not reloading when reentering (this worked with 0.0.11). When I turned on firebug I noticed an exception on every state change: 'state is undefined' happening on this line.

https://github.com/christopherthielen/ui-router-extras/blob/master/src/sticky.js#L440

**Comment by christopherthielen** [comment]
Doh. Likely unrelated. Are you using the new modular build, or full `ct-ui-router-extras.js`?  Could you put this into a plunkr for me?

**Comment by shanesmith** [comment]
Also running into @jvisser's issue so I've created a plunkr below.

http://plnkr.co/edit/po3jqSI7swYrAVaUFwxj?p=preview

Some quick sleuthing tell me that the bug is somehow related to https://github.com/christopherthielen/ui-router-extras/blob/master/src/transition.js#L43 and how it's used a few dozen lines below, probably should be returning `data` instead...
