### ISSUE TITLE
Prevent sticky parent state reload

### ISSUE THREAD

**Issue by hannupekka** [christopherthielen/ui-router-extras#205]
Hi

I'm using ui-router-extras for 2-level deep tab navigation. I've created Plunker post to better explain my problem: http://plnkr.co/edit/jSUGdJxxuROzNDYUjkBO?p=preview

To reproduce: 
1. Click tab2 on the left panel
2. Click tab2.bar on the left panel. Center and right panels now have the correct content
3. Click tab1
4. Click tab3. Center and right panels still have the correct content.
5. Click tab2. Center and right panels have lost their contents, which, I guess is because state bar2 has reloaded.

So I'm trying to build tab structure where the 1st level of navigation changes 2nd levels content and clicking 2nd level changes page content. 

This might be done better with simple ng-shows but the structure of the application is quite complex and states would help much.

Any idea how to implement this or is it even possible?

**Comment by christopherthielen** [comment]
There are two things I see going on your plunk:

- In step 5, you are activating the "tab2" state, not "tab2.bar".  Add `dsr: true` to the tab2 state definition to enable Deep State Redirect.
- Your two sticky-substates both fill in common named ui-views.  It's inevitable that one will clobber the other with that setup, even with `dsr: true`.  

I don't think this approach will work nicely.  It seems like "tab1/tab2/tab3" is just navigation and could be implemented with some directives, or something.  Also, the sticky states cannot share ui-views with other sticky states.  You'll likely have to resort to some show/hide things like in the example.  Sticky states are intended to be the root of an isolated state tree, which plugs into its own root named ui-view.  If two sticky states share the same layout, I'd probably share the layout template with each sticky state root instead of trying to re-use the same DOM elements for multiple sticky states (which doesn't work)

**Comment by christopherthielen** [comment]
Feel free to respond, but I'm cleaning out issues, so closing this
