### ISSUE TITLE
Support for Ui-Router 0.2.15

### ISSUE THREAD

**Issue by goodies4uall** [christopherthielen/ui-router-extras#234]
The latest ui-router contains some much needed fixes like reloadOnSearch 
https://github.com/angular-ui/ui-router/releases

**Comment by christopherthielen** [comment]
What features don't work with 0.2.15?

**Comment by goodies4uall** [comment]
I haven't found any yet just would be nice to have the official OK before moving into production.

**Comment by christopherthielen** [comment]
Extras should work with 0.2.15. :+1:

**Comment by anzorb** [comment]
I can't seem to get reloadOnSearch to work correctly with sticky states. I have 2 tabs, each backed by its own controller.

I need to be able to pass some params/search vars from step1 to step2, without reloading the controller. This is demostrated here using ui-router: http://plnkr.co/edit/5OPoKUDnn98JiKFlyEYL?p=preview

When using sticky states and router extras, reloadOnSearch is ignored and controller is destroyed and re-instantiated when the tab becomes visible again. Here's a plunker showing this behaviour: http://plnkr.co/edit/JOrtqK2EGOZxhO3cmRie?p=preview

Removing the ?update search param from the state stops it from re-instantiating, but I feel passing around params without re-instantiating the view would be the whole point of reloadOnSearch + ui-router-extras.

```
$stateProvider
    .state('tab1', {
      url: '/tab1',
      sticky: true,
      views: {
        tab1: {
          controller: 'Tab1Ctrl',
          templateUrl: 'tab1.html'
        }
      }
    })
    .state('tab2', {
      url: '/tab2?update',
      sticky: true,
      reloadOnSearch: false,
      views: {
        tab2: {
          controller: 'Tab2Ctrl',
          templateUrl: 'tab2.html'
        }
      }
    });
```
PS: Same behaviour is observed when using :param instead of search string.

**Comment by christopherthielen** [comment]
@anzorb yes, if reloadOnSearch is broken, there should be a separate ticket opened.
