### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by emilbayes** [christopherthielen/ui-router-extras#55]
Please publish to npm for easier use with browserify. [angular-ui/ui-router](https://github.com/angular-ui/ui-router) is already on npm.

**Comment by Pepelo** [comment]
@christopherthielen, it'd be really great if you can publish this to npm. Since you already have `package.json`, it is really easy. Here are the simple steps:
1. `cd` to your local repo
1. `npm adduser` (and enter your info/creds (don't worry if you don't have an account)... these are the same info/creds that will log you in to npmjs.com)
1. `npm publish`
That's it! :-)
Demo video: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by christopherthielen** [comment]
@Pepelo thank you, this is what I needed!

**Comment by christopherthielen** [comment]
https://www.npmjs.com/package/ui-router-extras

**Comment by Pepelo** [comment]
Thanks @christopherthielen! Appreciate it!
